<?php


namespace TD_Advertiser\src\classes\init;


use TD_Advertiser\src\classes\init\factories\TD_Navigation_Manager_Factory;
use TD_Advertiser\src\classes\interfaces\INavigation;
use TD_Advertiser\src\classes\TD_Advertiser_Base;
use TD_Advertiser\src\managers\TD_Advertiser_Base_Manager;

class TD_Advertiser_Navigation_Init extends TD_Advertiser_Base implements INavigation
{
    /**
     * @var TD_Advertiser_Base_Manager
     */
    private $manager;

    protected function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
    }


    function init()
    {
        global $_menu_hooks;
        $base_menu_url = 'banners-list';

        add_menu_page('Ads Banners','Ads Banners',$this->settings->getMenuCapability(),$base_menu_url,array($this,'menu_handler'),'',16.5);
        $_menu_hooks['banners-list'] = add_submenu_page($base_menu_url,__('Banners List'),__('Banners List'),$this->settings->getMenuCapability(),$base_menu_url,array($this,'menu_handler'));

        $_menu_hooks['banners-add-new'] = add_submenu_page($base_menu_url,__('Add New'),__('Add New'),$this->settings->getMenuCapability(),'post-new.php?post_type=td-advertiser');

        $_menu_hooks['banners-zones'] = add_submenu_page($base_menu_url,__('Ads Zones'),__('Ads Zones'),$this->settings->getMenuCapability(),'edit-tags.php?taxonomy=td_ads_zone&post_type=td-advertiser');

        add_action('admin_init',array($this,'admin_menu_request_handler'));
        add_action('admin_notices',array($this,'show_notifications'));

        $this->manager = TD_Navigation_Manager_Factory::getInstance()->getManager(isset($_REQUEST['page']) ? $_REQUEST['page'] : null);
    }

    function menu_handler()
    {
        if($this->manager)
            echo $this->manager->view_handler();
    }

    function admin_menu_request_handler()
    {
        if(($this->isSave() || ($this->isObjectId() && $this->isAction())) && $this->isPage()) {
            if($this->manager)
                $this->manager->redirect_handler();
        }
    }
    function show_notifications()
    {
        global $current_screen;

        if($error = get_transient('td_ads_error_handler'))
        {
            $out_error = '<div class="notice notice-'.$error['type'].'"><ul>';
            $out_error.='<li>'.$error['message'].'</li>';
            $out_error.="</ul></div>";
            delete_transient('td_ads_error_handler');
            echo $out_error;
        }
    }
}