<?php


namespace TD_Advertiser\src\tables;


use TD_Advertiser\src\object\Banner;
use TD_Advertiser\src\repository\impl\Banners;

class TD_Advertiser_Banners_List_Table extends TD_Advertiser_List_Table
{

    public function __construct($args = array())
    {
        $this->db_ctx = $args['dbc'];
        $default = array(
            'screen'=>\WP_Screen::get($args['post_type'])
        );

        $args = wp_parse_args($args,$default);
        parent::__construct($args); // TODO: Change the autogenerated stub
    }

    public function get_columns()
    {
        $columns = array(

            'title' => 'Title',
            'zone' =>'Ads Zone',
            'banner_type'=>'Type',
            'show_on'=>'Show On',
            'location'=>'location',
            'views'=>'Views',
            'price'=>'Price',
            'date_limits'=>'Date Limits',
            'added_at'=>'Added At',
            'status'=>'Status'
        );

        return $columns;

    }

    /**
     * @param Banner $item
     * @return string
     */
    function column_title($item)
    {
        return $item->getBannerTitle();
    }

    /**
     * @param Banner $item
     * @return mixed
     */
    function column_banner_type($item)
    {
        return $item->getBannerAdsType();
    }

    /**
     * @param Banner $item
     * @return string
     */
    function column_zone($item)
    {
        $zones = wp_get_post_terms($item->getId(),'td_ads_zone',array('fields'=>'names'));
        return join(', ',$zones);
    }

    /**
     * @param Banner $item
     * @return string
     */
    function column_location($item)
    {
        return ucfirst($item->getBannerPosition());
    }

    /**
     * @param Banner $item
     * @return int
     */
    function column_views($item)
    {
        return $item->getViews();
    }

    /**
     * @param Banner $item
     * @return string
     */
    function column_price($item)
    {
        return sprintf("Rate per view %s <br> Total: %s",$item->getPricePerView(),$item->getViews()*$item->getPricePerView());

    }

    /**
     * @param Banner $item
     * @return string
     */
    function column_date_limits($item)
    {
        if($item->isBannerDatesLimits())
        {
            return sprintf('Start: %s <br> End: %s',$item->getBannerStartDate()->format('d-m-Y'),$item->getBannerEndDate()->format('d-m-Y'));
        }
        return 'unlimited';
    }

    /**
     * @param Banner $item
     * @return mixed
     */
    function column_added_at($item)
    {
        return $item->getCreatedAt()->format('d-m-Y');
    }

    /**
     * @param Banner $item
     * @return mixed
     */
    function column_status($item)
    {
        return $item->isBannerStatus()?'Active':'Disabled';
    }
    /**
     * @param Banner $item
     * @return array
     */
    function column_show_on($item)
    {
        return join(',<br>',array_map(array($this,"show_on_mapper"),$item->getBannerShowOn()));
    }
    protected  function show_on_mapper($a)
    {
        return ucfirst($a)."";
    }

    protected function get_default_primary_column_name()
    {
        return 'title';
    }

    public function prepare_items()
    {

        $this->_column_headers  = $this->get_column_info();
        $this->items = $this->db_ctx->getBanners()->getAll();

    }

    protected function column_default($item, $column_name)
    {
        switch($column_name)
        {

            default:
                return $item->getId();
        }
    }

    /**
     * @param Banner $item
     * @param string $column_name
     * @param string $primary
     * @return string
     */
    protected function handle_row_actions($item, $column_name, $primary)
    {
        if($column_name!=$primary) return '';
        //http://localhost/wplab_2/wp-admin/post.php?post=16115&action=edit

        $actions = array();
        $edit = add_query_arg(array('post'=>$item->getId(),'action'=>'edit'),admin_url('post.php'));
        $del = add_query_arg(array('page'=>$_REQUEST['page'],'a'=>'del','id'=>$item->getId()),admin_url('admin.php'));


        $actions['edit'] = sprintf('<a href="%s">%s</a>',$edit,__('Edit'));
        $actions['delete'] = sprintf('<a href="%s">%s</a>',$del,__('Delete'));

        return $this->row_actions($actions);
    }

    public function add_new_button()
    {
        //http://localhost/wplab_2/wp-admin/post-new.php?post_type=td-advertiser
        $add_new = add_query_arg(array('post_type'=>$this->_args['post_type']),admin_url('post-new.php'));
        echo sprintf('<a href="%s" class="page-title-action">%s</a><hr class="wp-header-end">',$add_new,__("Add New"));
    }

    protected function custom_table_css_classes()
    {
        return "table-ads-banner-list";
    }


}