<?php


namespace TD_Advertiser\src\short_codes\src\impl;


use TD_Advertiser\src\short_codes\src\TD_Ads_Short_Codes_Base;
use WP_Query;

class TD_Ads_Set_Single_Zone extends TD_Ads_Short_Codes_Base
{
    public function __construct()
    {
        parent::__construct('td_ads_single_zone'); // TODO: Change the autogenerated stub
        $this->short_code_title = "Ads Single Layout";

    }


    function render($attr, $content)
    {
        $this->params = shortcode_atts($this->default_options,$attr);
        return $this->show_layout();
    }

    function base_params()
    {
        $zones['default']='';
        $zones = array_merge($zones,$this->get_ads_zones_list());

        $params_sc = array();
        $params_sc[] = array (
            'type' =>'dropdown' ,
            'heading' =>'Select Zones' ,
            'param_name' =>'ads_zone' ,
            'value'=>$zones,
            'save_always' => true,
            'description' =>'Select Zone what banners have to be shown',
        );

        $params_sc[] = array(
            'type'=>'textfield',
            'heading'=>'Select Banner',
            'param_name'=>'ads_banner',
            'description'=>'Enter the ID of the banner you want to display in selected zone',
            'value'=>'',
            'dependency'=>array(
                'element'=>'ads_zone',
                'value'=>array_values(array_filter($zones,function($e){return !empty($e);})),

           )
        );

        //var_dump($params_sc[1]['dependency']);


        return $params_sc;

    }
    private function get_ads_zones_list()
    {
        $args = array(
            'taxonomy'=>'td_ads_zone',
            'fields'=>'id=>name'
        );
       $terms =  get_terms($args);

        $zones = array();
        foreach($terms as $k=>$v)
        {
            $zones[$v]=''.$k;
        }
        return $zones;
    }
    private  function show_layout()
    {

        $zone = get_term($this->params['ads_zone'],'td_ads_zone');
        $this->params['banner_obj_ID']=null;
        $this->params['zone_obj']=null;
        if($zone)
        {
            $this->params['zone_obj']=$zone;
        $args = array(
                'post_type' => 'td-advertiser',
                'posts_per_page' => '1',
                'td_ads_zone' => $zone->slug,
                'orderby'=>'date',
                'order' => 'DESC',
                'post_status' => 'publish',
            );
            if(isset($this->params['ads_banner']) && !empty($this->params['ads_banner']))
                $args['p']=$this->params['ads_banner'];

            $query = new WP_Query($args);
            wp_reset_postdata();

            if($query->post_count>0)
                $this->params['banner_obj_ID'] = $query->post->ID;
        }
        return $this->View('single_layout',array_merge(array('obj'=>$this),$this->params));
    }


}