<?php


namespace TD_Advertiser\src\managers;


use TD_Advertiser\src\classes\TD_Advertiser_Base;
use TD_Advertiser\src\exceptions\TD_Advertiser_Exception;

abstract class TD_Advertiser_Base_Manager extends TD_Advertiser_Base
{
    protected function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
    }
    public abstract function init_manager_routes();
    protected abstract function show();
    protected abstract function delete($id);
    protected function init_routes()
    {
        $_REQUEST['a'] = (isset($_REQUEST['a']) && !empty($_REQUEST['a'])) ? $_REQUEST['a'] : 'show';
        switch($_REQUEST['a']) {
            case 'show':
                $this->show();
                break;
            case 'del':
                $this->delete($_REQUEST['id']);
                break;
        }
    }
    protected function showMessage($message_type,$message)
    {
        $this->settings->setNotify(array('type'=>$message_type,'message'=>$message));
    }

    public function view_handler()
    {
        try{
            $this->init_manager_routes();
        }catch(TD_Advertiser_Exception $ex)
        {
            $this->showMessage("error",$ex->getMessage());
        }
        return $this->View($this->settings->getView(),array_merge(array("obj"=>$this),$this->settings->getParams()));
    }

    public function redirect_handler()
    {

        try{

            $this->init_manager_routes();

            $this->settings->setPage($_REQUEST['page']);
            $query=add_query_arg(array($this->settings->getParams()),admin_url('admin.php'));
            wp_redirect($query);
            exit;

        }catch(\Exception $ex)
        {
            $this->showMessage("error",$ex->getMessage());
            wp_redirect(add_query_arg(array('page' => $_REQUEST['page'], $this->settings->getParams()), admin_url('admin.php')));
            exit;

        }

    }
    function View($viewName, $params=array())
    {

        if(is_array($params) && count($params)) {
            extract($params);
        }
        $file = TD_ADVERTISER_PLUGIN_DIR . 'src/view/'. $viewName . '.php';

        ob_start();
        include( $file );
        $ret_obj= ob_get_clean();


        return $ret_obj;
    }

    public function init()
    {
        // TODO: Implement init() method.
    }

}